<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48-windows</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <OutputType>Library</OutputType>
    <AssemblyName>AutomatedClashRunner</AssemblyName>
    <RootNamespace>AutomatedClashRunner</RootNamespace>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Autodesk.Navisworks.Api">
      <HintPath>C:\Program Files\Autodesk\Navisworks Manage 2024\Autodesk.Navisworks.Api.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Autodesk.Navisworks.Clash">
      <HintPath>C:\Program Files\Autodesk\Navisworks Manage 2024\Autodesk.Navisworks.Clash.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>
